Always upgrade packages to avoid version conflicts when pip declines to upgrade an old package
Requirement already satisfied: pytest>=3.1 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from -r dev_requirements.txt (line 3))
...
pluggy.PluginValidationError: Plugin 'flake8' could not be loaded: (pytest 3.3.0 (/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.5'))!